pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'master',
                    credentialsId: .env(github-creds),
                    url: 'https://github.com/zaydAntony/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest messaging_app --junitxml=test-report.xml
                '''
            }
        }

        stage('Generate Test Report') {
            steps {
                junit 'test-report.xml'
            }
        }
    }
}
