pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "zaydantony123@gmail.com/messaging_app"
        DOCKER_TAG = "latest"
    }

    tools {
        python 'python3'
    }

    stages {

        stage('Checkout Code') {
            steps {
                git credentialsId: .env(github-creds),
                    url: 'https://github.com/ZaydAntony/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest messaging_app --junitxml=report.xml
                '''
            
        }

        stage('Publish Test Report') {
            steps {
                junit 'report.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                cd messaging_app
                docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: .env(dockerhub-creds),
                    usernameVariable: .env(DOCKER_USER),
                    passwordVariable: .env(DOCKER_PASS)
                )]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    docker push $DOCKER_IMAGE:$DOCKER_TAG
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Docker image built and pushed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
