#!/bin/bash

echo " Deploying BLUE version..."
kubectl apply -f blue_deployment.yaml

echo " Deploying GREEN version..."
kubectl apply -f green_deployment.yaml

echo " Applying service..."
kubectl apply -f kubeservice.yaml

echo " Waiting for green pods to start..."
sleep 10

echo " Checking logs for GREEN deployment..."
GREEN_PODS=$(kubectl get pods -l version=green -o jsonpath="{.items[*].metadata.name}")

for pod in $GREEN_PODS; do
  echo " Logs for $pod"
  kubectl logs "$pod"
done

echo "Blue-Green deployment completed"
